# Generated by Django 3.0.4 on 2020-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCN_notice',
            fields=[
                ('NOTICE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NOTICE_TYPE', models.IntegerField()),
                ('NOTICE_TEL_ID', models.IntegerField()),
                ('TRIGGER_NUM', models.IntegerField()),
                ('GRB_DATE', models.DateField()),
                ('GRB_TIME', models.TimeField()),
                ('GRB_RA', models.FloatField()),
                ('GRB_RA_hms', models.CharField(max_length=45)),
                ('GRB_DEC', models.FloatField()),
                ('GRB_RA_dms', models.CharField(max_length=45)),
                ('GRB_ERROR', models.FloatField()),
                ('TRIGGER_SIGNIF', models.FloatField()),
                ('TRIGGER_DUR', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
